stages:
  - build

build-ubuntu:
  stage: build
  image: registry.gitlab.com/nxxm/nxxm/ci/ubuntu-cpp:latest
  script:
    - mkdir build/ && cd build/ && cmake .. -DCMAKE_TOOLCHAIN_FILE=deps/polly/gcc-7-cxx17.cmake -DUNIT_TESTS=ON && cmake --build . && ctest . --verbose

build-macos:
  stage: build
  tags:
    - macOS
  script:
    - mkdir build/ && cd build/ && cmake .. -DCMAKE_TOOLCHAIN_FILE=deps/polly/clang-cxx17.cmake -DUNIT_TESTS=ON && cmake --build . && ctest . --verbose

build-win:
  stage: build
  tags:
    - win10
  script:
    - set PreferredToolArchitecture=x64
    - mkdir build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=deps/polly/cxx17.cmake -DUNIT_TESTS=ON && cmake --build . && ctest . -C Debug --verbose
