version: "{build}"

branches:
  except:
    - gh-pages
    - traits

skip_tags : true
shallow_clone: true

os: Visual Studio 2015

environment:
  matrix:
    - TITLE: vc2015
      COMPILER: Visual Studio 14 2015
    - TITLE: vc2008
      COMPILER: Visual Studio 9 2008
    - TITLE: vc2010
      COMPILER: Visual Studio 10 2010
    - TITLE: vc2012
      COMPILER: Visual Studio 11 2012
    - TITLE: vc2013
      COMPILER: Visual Studio 12 2013

install:
  - git clone --depth 1 https://github.com/CxxTest/cxxtest.git

build_script:
  - set CL=/I C:\projects\better-enums\cxxtest
  - set PATH=%PATH%;C:\projects\better-enums\cxxtest\bin;C:\cygwin\bin
  - cd test
  - make ms
