name: build 
on: [push]

jobs:
  build: 
    name: build-linux
    runs-on: ubuntu-latest
    container: tipibuild/tipi-ubuntu
    env:
      GH_USER: nxxmgh
      GH_PASS: ${{ secrets.USER_PAT_NXXMGH_TOKEN_FOR_GH }}
      GH_RELEASE_TEST_REPO_OWNER: nxxm
      GH_RELEASE_TEST_REPO_NAME: gh
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: tipi builds project 
        run: |
          export HOME=/root
          mkdir -p ~/.tipi
          tipi . -t linux-cxx17 --dont-upgrade --verbose --test all 
